version: '3.8'

services:
  app:
    image: webdevops/php-apache:8.2
    ports:
      - "8080:80"
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=secret_clinica_db_pass
      - DB_NAME=clinica_db
      - BASE_URL=http://localhost:8080 # Altere em produção
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret_clinica_db_pass
      - MYSQL_DATABASE=clinica_db
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
