version: '3.8'

services:
  # Container inicial que baixa o código do Github direto pro volume do Docker
  git-sync:
    image: alpine/git
    entrypoint: /bin/sh
    command: -c "if [ -d /app/.git ]; then cd /app && git fetch --all && git reset --hard origin/main; else git clone https://github.com/tvagenciariver/clinica-medwork.git /app; fi; mkdir -p /app/public/uploads; chmod -R 777 /app/public/uploads"
    volumes:
      - app_code:/app

  app:
    image: webdevops/php-apache:8.2
    ports:
      - "9090:80"
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=secret_clinica_db_pass
      - DB_NAME=clinica_db
    volumes:
      - app_code:/app
    depends_on:
      - git-sync
      - db

  db:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=secret_clinica_db_pass
      - MYSQL_DATABASE=clinica_db
    volumes:
      - db_data:/var/lib/mysql

  db-init:
    image: mariadb:10.5
    command: sh -c "while ! mysqladmin ping -h db -u root -psecret_clinica_db_pass --silent; do sleep 2; done; while [ ! -f /app/init.sql ]; do sleep 1; done; mysql -h db -u root -psecret_clinica_db_pass clinica_db < /app/init.sql"
    volumes:
      - app_code:/app
    depends_on:
      - db

volumes:
  app_code:
  db_data:
